export enum ErrorCode {
  BAD_USER_INPUT = "BAD_USER_INPUT",
  UNAUTHENTICATED = "UNAUTHENTICATED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_AUTHORIZED = "NOT_AUTHORIZED",
  CART_NOT_FOUND = "CART_NOT_FOUND",
}
